// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_emoji_get_emojis from "./routes/api/emoji/get-emojis.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $EmojiInput from "./islands/EmojiInput.tsx";
import * as $EmojiTab from "./islands/EmojiTab.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/emoji/get-emojis.ts": $api_emoji_get_emojis,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/EmojiInput.tsx": $EmojiInput,
    "./islands/EmojiTab.tsx": $EmojiTab,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
